# Generated by Django 4.2.1 on 2024-07-09 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('cod_aud', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('objetivo', models.CharField(blank=True, max_length=600)),
                ('fec_ini', models.DateField(blank=True, null=True)),
                ('fec_ter', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('S', 'Suspendida'), ('C', 'Cerrada'), ('E', 'En Ejecucion'), ('P', 'En Planificacion')], default='C', help_text='Estado de la definicion del Proceso', max_length=1)),
                ('nro_modulos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('codigo_frame', models.CharField(blank=True, max_length=10, unique=True)),
                ('fw_nombre', models.CharField(blank=True, max_length=200)),
                ('fw_version', models.CharField(blank=True, max_length=10)),
                ('fw_descrip', models.CharField(blank=True, max_length=400)),
                ('fw_inst', models.CharField(blank=True, max_length=150)),
                ('nro_modulos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_aud', models.IntegerField(default=0)),
                ('pk_padre', models.IntegerField(default=0)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('item', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('nro_submodulos', models.IntegerField(default=0)),
                ('nro_objetivos', models.IntegerField(default=0)),
                ('abierto', models.BooleanField(default=False)),
                ('auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='CIS.auditorias')),
            ],
            options={
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='Modulo_Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_frw', models.IntegerField(default=0)),
                ('pk_padre', models.IntegerField(default=0)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('item', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('nro_submodulos', models.IntegerField(default=0)),
                ('nro_objetivos', models.IntegerField(default=0)),
                ('abierto', models.BooleanField(default=False)),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework', to='CIS.framework')),
            ],
            options={
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='Parametros_G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('valor_1', models.CharField(blank=True, max_length=15)),
                ('valor_2', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_OC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_oc_nombre', models.CharField(blank=True, max_length=20)),
                ('tipo_oc_descripcion', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Obj_Ries_Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_padre', models.IntegerField(default=0)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('obj_item', models.CharField(blank=True, max_length=20)),
                ('obj_nombre', models.CharField(blank=True, max_length=100)),
                ('obj_descripcion', models.CharField(blank=True, max_length=600)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo', to='CIS.modulo_mod')),
            ],
            options={
                'ordering': ['obj_item'],
            },
        ),
        migrations.CreateModel(
            name='Obj_Ries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_padre', models.IntegerField(default=0)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('obj_item', models.CharField(blank=True, max_length=20)),
                ('obj_nombre', models.CharField(blank=True, max_length=100)),
                ('obj_descripcion', models.CharField(blank=True, max_length=600)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo_a', to='CIS.modulo')),
            ],
            options={
                'ordering': ['obj_item'],
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField(null=True)),
                ('cargo', models.CharField(blank=True, max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50)),
                ('fono_t', models.CharField(blank=True, max_length=50)),
                ('fono_c', models.CharField(blank=True, max_length=50)),
                ('user_gestor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.AddField(
            model_name='framework',
            name='fw_modulos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_sup', to='CIS.modulo_mod'),
        ),
        migrations.AddField(
            model_name='auditorias',
            name='auditor_ejec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_ejec', to='CIS.gestor'),
        ),
        migrations.AddField(
            model_name='auditorias',
            name='auditor_sup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_sup', to='CIS.gestor'),
        ),
        migrations.AddField(
            model_name='auditorias',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Frame_Work', to='CIS.framework'),
        ),
    ]
