# Generated by Django 4.2.1 on 2024-07-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='codigo_frame',
        ),
    ]
